"""new parent modell

Revision ID: 4c86e6639b37
Revises: a85a1b95040a
Create Date: 2024-10-19 13:53:40.729669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c86e6639b37'
down_revision = 'a85a1b95040a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ziel_historie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ziel_id', sa.Integer(), nullable=False),
    sa.Column('geändert', sa.DateTime(), nullable=True),
    sa.Column('bewertung', sa.Integer(), nullable=False),
    sa.Column('abteilung', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ziel_id'], ['ziel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ziel_historie')
    # ### end Alembic commands ###
