"""first migration

Revision ID: a85a1b95040a
Revises: 
Create Date: 2024-10-17 10:40:24.634780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85a1b95040a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ziel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abteilung', sa.String(length=50), nullable=False),
    sa.Column('aussage', sa.String(length=255), nullable=True),
    sa.Column('kriterium', sa.String(length=255), nullable=True),
    sa.Column('bewertung', sa.Integer(), nullable=True),
    sa.Column('einschätzung', sa.String(length=255), nullable=True),
    sa.Column('geändert', sa.DateTime(), nullable=False),
    sa.Column('kommentar', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ziel')
    # ### end Alembic commands ###
